### ISSUE TITLE
restic-restore-helper container doesn't run when pod has runAsNonRoot: true

### ISSUE THREAD

**Issue by JonDGH** [vmware-tanzu/velero#2437]
**What steps did you take and what happened:**

Annotate pods with: backup.velero.io/backup-volumes: data
velero backup create my-data-backup --include-namespaces=jon-test-system

backup completes successfully

oc delete namespace jon-test-system
velero restore create --from-backup=my-backup --restore-volumes --include-resources=pvcs,pvs

(I don't think the --include-resources argument is required)

Most of the resources are restored correctly, however pods with:

```
  securityContext:
    runAsNonRoot: true
    seLinuxOptions:
      level: s0:c37,c19
```

Fail with:

```
  initContainerStatuses:
  - image: velero/velero-restic-restore-helper:v1.3.2
    imageID: ""
    lastState: {}
    name: restic-wait
    ready: false
    restartCount: 0
    state:
      waiting:
        message: container has runAsNonRoot and image has non-numeric user (nobody),
          cannot verify user is non-root
        reason: CreateContainerConfigError
```

**What did you expect to happen:**

All resources and volumes restored correctly.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  creationTimestamp: "2020-04-15T08:05:06Z"
  generation: 3
  labels:
    velero.io/storage-location: default
  name: my-data-backup
  namespace: jon-velero
  resourceVersion: "11884425"
  selfLink: /apis/velero.io/v1/namespaces/jon-velero/backups/my-data-backup
  uid: 5a4173fb-909e-486e-ba1b-adf1eb65ba08
spec:
  hooks: {}
  includedNamespaces:
  - jon-test-system
  includedResources:
  - pvs
  - pvcs
  storageLocation: default
  ttl: 720h0m0s
status:
  completionTimestamp: "2020-04-15T08:06:12Z"
  expiration: "2020-05-15T08:05:06Z"
  phase: Completed
  startTimestamp: "2020-04-15T08:05:06Z"
  version: 1
```

* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
apiVersion: velero.io/v1
```
kind: Restore
metadata:
  creationTimestamp: "2020-04-15T12:25:48Z"
  generation: 2
  name: my-data-backup-20200415132548
  namespace: jon-velero
  resourceVersion: "12031491"
  selfLink: /apis/velero.io/v1/namespaces/jon-velero/restores/my-data-backup-20200415132548
  uid: a52a2b83-adb9-499b-8de4-a7cda9b40f26
spec:
  backupName: my-data-backup
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  includedNamespaces:
  - '*'
  restorePVs: true
status:
  phase: InProgress
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):v1.3.2 55a9914a3e4719fb1578529c45430a8c11c28145
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`):
$ oc version
Client Version: 4.3.5
Server Version: 4.3.0
Kubernetes Version: v1.16.2
- Cloud provider or hardware configuration: OpenShift
- OS (e.g. from `/etc/os-release`):
	- RuntimeOS: windows	- RuntimeArch: amd64

**Comment by JonDGH** [comment]
I tried to reproduce this is in a microk8s environment (had to run:

```
microk8s.kubectl patch ds/restic \
  --namespace velero \
  --type json \
  -p '[{"op":"replace","path":"/spec/template/spec/volumes/0/hostPath","value": { "path": "/var/snap/microk8s/common/var/lib/kubelet/pods"}}]'
```
)

but the backup only included a single volume, so didn't get as far as attempting the restore.

**Comment by snorwin** [comment]
@eleanor-millman why this not fixable? Can you not just use a numeric user e.g. `1001`?

**Comment by dsu-igeek** [comment]
Re-opening for more detailed investigation

**Comment by zubron** [comment]
As discussed in the community meeting with @sseago, we need to investigate whether we can change just the velero-restic-restore-helper to use the UID directly rather than `nonroot` user. This would require changes to our build process as we use the same Dockerfile for both the velero and velero-restic-restore-helper images.

**Comment by benjvi** [comment]
Ran into this issue last week while trying to migrate a cluster. In the absence of a fix, we were able to use the following commands to identify pods that would be affected by this issue if restic needs to restore any volumes to them (in our case, we had velero setup to backup all volumes):

```
kubectl get po -A -o json | jq '.items[] | select(.spec.securityContext.runAsNonRoot == true and .spec.securityContext.runAsUser == null and .status.phase == "Running" ) | .metadata.name'
```

AFAICT the only workaround right now is to update the config for those affected workloads or exclude those volumes from backup/restore

**Comment by glimpsec** [comment]
We used the following Kyverno policy as a workaround to restore a pvc where the backed-up pod already had this securityContext. The admission controller patches the pod spec when Velero creates the pod. Because this creates a mismatch between deployment/statefulset spec and podspec, we only selected the pod/pv/pvc in our restore. Alternatively one could probably patch both the Deployment and Pod specs.

```
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  annotations:
    policies.kyverno.io/description: Remove the securitycontext runAsNonRoot=true as workaround for a Restic restore issue.
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/title: Mutate securitycontext runasnonroot
  name: remove-runasnonroot
spec:
  rules:
  - match:
      resources:
        kinds:
        - Pod
    mutate:
        patchesJson6902: |-
          - path: "/spec/securityContext/runAsNonRoot"
            op: remove 
    name: remove-runasnonroot

```

**Comment by tkanters** [comment]
This issue seems to have been fixed in openshift/velero (https://github.com/openshift/velero/issues/122). It it hasn't been released yet though and I also don't see a mention of it being backported to velero.

**Comment by waldner** [comment]
Still seeing this with velero 1.11.1, has there been any progress?

**Comment by Heiko-san** [comment]
open since 2020 ... when will this be fixed? ^^ (ran into the very same issue just now)

**Comment by inzanez** [comment]
Is there any decent way of restoring such a backup? Not really sure, but for now it looks like such a backup is pretty much useless? ...

**Comment by blackpiglet** [comment]
There is a customized ConfigMap for the filesystem backup restore helper.
https://velero.io/docs/v1.13/file-system-backup/#customize-restore-helper-container

Users can specify the permission, UID, and GID preferred.

**Comment by inzanez** [comment]
Not sure why that might be but these settings are not applied to the `restore-wait` init container, so it still fails...

**Comment by blackpiglet** [comment]
@inzanez 
What's the version of Velero you are using?
I think this should be fixed in https://github.com/vmware-tanzu/velero/releases/tag/v1.9.0

The fix PR is https://github.com/vmware-tanzu/velero/pull/4084.
IMO, this issue should be closed.

**Comment by inzanez** [comment]
@blackpiglet
```
Client:
        Version: v1.13.0
        Git commit: 76670e940c52880a18dbbc59e3cbee7b94cd3352
Server:
        Version: v1.13.0
```

So it seems I must be doing something wrong...I added a configmap like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fs-restore-action-config
  namespace: velero
  labels:
    velero.io/pod-volume-restore: RestoreItemAction
data:
  secCtxRunAsUser: "1001"
  secCtxAllowPrivilegeEscalation: "false"

```

But the `wait` container does not get any user applied.

**Comment by inzanez** [comment]
Ok, I see, the empty label `velero.io/plugin-config: ""` is required. That changes quite a lot, now it's just all about permissions and getting them right during the restore. Thanks!
