### ISSUE TITLE
Restic backup fails with Fatal: invalid id \"8bcb4ae8\": no matching ID found\n

### ISSUE THREAD

**Issue by VincenzoDo** [vmware-tanzu/velero#2507]
**What steps did you take and what happened:**
We have a daily schedule that does restic backup of around 120 volumes to s3. 
Only a part of the volumes are successfully backed up. Let's say out of 120, 67 succeed and the rest failed with the following error: 

Fatal: invalid id \"8bc4dae8\": no matching ID found\n

The same happens when I trigger one of the failed backup manually. As far as I can see there is no difference from the PVC that succeeds and one that fails.

**What did you expect to happen:**
All volumes are backed up successfully.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
https://pastebin.com/MrVKQe3f
* `velero backup logs <backupname>`
https://pastebin.com/2PrfCLQz

**Anything else you would like to add:**
I can provide more logs if needed

**Environment:**

- Velero version (use `velero version`): 1.2.0
- Velero features (use `velero client config get features`): -
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by skriss** [comment]
@VincenzoDo do you have more than one BackupStorageLocation that you're using, i.e. does `velero backup-location get` show more than one item?

**Comment by skriss** [comment]
You may be hitting some combination of https://github.com/vmware-tanzu/velero/issues/2192 and https://github.com/vmware-tanzu/velero/issues/2185, both of which have been fixed in the v1.3 series. I'd recommend starting by upgrading your Velero deployment & daemonset to `v1.3.2`.

**Comment by VincenzoDo** [comment]
Hello @skriss, no just one:
```
velero backup-location get
NAME      PROVIDER   BUCKET/PREFIX       ACCESS MODE
default   aws        prometheus-backup   ReadWrite
```

**Comment by VincenzoDo** [comment]
I updated both images to the latest version but the problem persists, same errors. Any other suggestions? Is there a place where I can see a more detailed error than:
`stderr=Fatal: invalid id \"47462d79\": no matching ID found\n: unable to find summary in restic backup command output"`

**Comment by ashish-amarnath** [comment]
@VincenzoDo Does this https://github.com/vmware-tanzu/velero/issues/2109#issuecomment-562551041 apply to your case here?

**Comment by VincenzoDo** [comment]
Hi, not really. As far as I understood the comment says that all backups are failing, while in my case it's only like 40% of the backups. I'm off work this week, when I'm back I will try to re-install velero...

**Comment by rust84** [comment]
I had this issue with a couple of the pods and it was only resolved with a full reset of velero, removed all crds, bucket etc. I had upgraded from 1.2 to 1.3 previously. So far it hasn't reoccurred.

**Comment by VincenzoDo** [comment]
So I re-deployed velero. I used commands suggested in the doc to delete all deployments and custom resource definition.

The first backup I took of all statefulsets (and pvcs) had around 20 failures. After seeing a timeout related error in the logs I increase the timeout (  - --restic-timeout=6h" ).

The second backup I took had only 2 failures (with the usual error):
```
time="2020-05-24T23:36:27Z" level=error msg="Error backing up item" backup=velero/daily-20200524230041 error="pod volume backup failed: error running restic backup, stderr=Fatal: invalid id \"ce83b646\": no matching ID found\n: unable to find summary in restic backup command output" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:182" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:287" name=prometheus-0 namespace= resource=pods
```
Today it's again up to 23 failures.

Might be related to https://github.com/vmware-tanzu/velero/issues/2539

Should I try a deployment with debug log level?

**Comment by VincenzoDo** [comment]
Upgraded to version 1.4 but still getting errors:
```
time="2020-06-18T02:10:42Z" level=error msg="Error backing up item" backup=velero/daily-20200617230018 error="pod volume backup failed: error running restic backup, stderr=: unable to find summary in restic backup command output" error.file="/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:179" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:448" name=prometheus-0
```

**Comment by ashish-amarnath** [comment]
@VincenzoDo Can you please tell us what provider you are using to provision volumes?
Can you also please try the troubleshooting steps from https://github.com/vmware-tanzu/velero/issues/2539#issuecomment-641532094, https://github.com/vmware-tanzu/velero/issues/2539#issuecomment-655176937,  and https://github.com/vmware-tanzu/velero/issues/2539#issuecomment-655659903 and

**Comment by ashish-amarnath** [comment]
I am closing this issue for inactivity. But please re-open or reach out if you have more questions or need help troubleshooting.

**Comment by prabhinmp** [comment]
Im also facing the same issue,
`time="2021-09-28T10:38:24Z" level=error msg="Error backing up item" backup=velero/daily-backup-20210928103822 error="pod volume backup failed: error running restic backup, stderr=Fatal: invalid id \"5c38d1c5\": no matching ID found for prefix \"5c38d1c5\"\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:179" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:431" name=-es-master-0`

**Comment by jordanvrtanoski** [comment]
I have experienced same issue. 

```
time="2023-03-30T20:35:47Z" level=error msg="Error backing up item" backup=velero/backup-orc8r-20230331 error="pod volume backup failed: running backup, stderr=error running restic backup command restic backup --repo=s3:http://10.255.16.30:9000/backup/restic/orc8r --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic . --tag=backup-uid=51cc33db-2d4a-4999-9887-9b1f76e06366 --tag=ns=orc8r --tag=pod=postgresql-0 --tag=pod-uid=23267ebb-50b5-439e-ad13-910c4ca206a6 --tag=pvc-uid=a80266da-8d16-4b97-b8bb-4d00af0dd801 --tag=volume=data --tag=backup=backup-orc8r-20230331 --host=velero --json --parent=4fa9fb42 with error: exit status 1 stderr: Fatal: invalid id \"4fa9fb42\": no matching ID found for prefix \"4fa9fb42\"\n: error running restic backup command restic backup --repo=s3:http://10.255.16.30:9000/backup/restic/orc8r --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic . --tag=backup-uid=51cc33db-2d4a-4999-9887-9b1f76e06366 --tag=ns=orc8r --tag=pod=postgresql-0 --tag=pod-uid=23267ebb-50b5-439e-ad13-910c4ca206a6 --tag=pvc-uid=a80266da-8d16-4b97-b8bb-4d00af0dd801 --tag=volume=data --tag=backup=backup-orc8r-20230331 --host=velero --json --parent=4fa9fb42 with error: exit status 1 stderr: Fatal: invalid id \"4fa9fb42\": no matching ID found for prefix \"4fa9fb42\"\n" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:223" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:425" name=postgresql-0
```

While the backup was in progress, I have modified the CPU limits for the `node-agent` in the deployment after which the pods ware automatically recreated. The backup in progress had failed and all subsequent backups ware failing with the same issue.
Issue was resolved after uninstalling velero, recreating the S3 bucket and installing velero again.
It looks like restic is corrupting the repository when the pod is restarted while performing the backup.

**Comment by ugur99** [comment]
We've experienced the same issue here:
```
velero-74bd7957bd-htm86 velero time="2023-05-05T09:16:01Z" level=error msg="Error backing up item" backup=velero/ugur-test-backup-03 error="pod volume backup failed: running backup, stderr=error running restic backup command restic backup --repo=s3:https://internal:9000/velero-test/restic/test --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cacert=/tmp/cacert-default505211303 --cache-dir=/scratch/.cache/restic . --tag=pod=data-8569664dbb-9rr4c --tag=pod-uid=6ba418fd-7f82-446b-b398-b39b81e351d5 --tag=pvc-uid=41b1e50d-b554-4363-834a-fd3fe2d4c240 --tag=volume=data --tag=backup=ugur-test-backup-03 --tag=backup-uid=c268bc89-1d52-46bb-a36b-38fe4a475bc3 --tag=ns=test --host=velero --json --parent=f07ec467 with error: exit status 1 stderr: no matching ID found for prefix \"f07ec467\"\n: error running restic backup command restic backup --repo=s3:https://internal:9000/velero-test/restic/test --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cacert=/tmp/cacert-default505211303 --cache-dir=/scratch/.cache/restic . --tag=pod=data-8569664dbb-9rr4c --tag=pod-uid=6ba418fd-7f82-446b-b398-b39b81e351d5 --tag=pvc-uid=41b1e50d-b554-4363-834a-fd3fe2d4c240 --tag=volume=data --tag=backup=ugur-test-backup-03 --tag=backup-uid=c268bc89-1d52-46bb-a36b-38fe4a475bc3 --tag=ns=test --host=velero --json --parent=f07ec467 with error: exit status 1 stderr: no matching ID found for prefix \"f07ec467\"\n" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:250" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:435" name=data-8569664dbb-9rr4c
```
Velero Server version: `v1.11.0`
Node Agent version: `v1.11.0`

I enabled debug mode but still no more insightful logs, do you have any troubleshooting suggestions for such cases? I checked [troubleshooting page](https://velero.io/docs/v1.11/troubleshooting/) but did not find anything for that case. And for sure I'll appreciate any kind of helps :)

**Comment by optimus-kart** [comment]
is there any workaround for this issue other than re-installing the service with a new bucket?

**Comment by optimus-kart** [comment]
Found a way to workaround this issue,
 So the problem is that the velero triggers a restic backup using the podvolumebackups available in the system as parent, now if the snapshotID of backup in the pvb is not present, the restic command will fail with "no matching ID found for prefix", so to overcome this issue, you have to delete the pvb corresponding to the volume that is failing, In my case I had to delete all previous pvb for that volume since none of those snapshot ids were present, once this is done, you can trigger the backup again

**Comment by GeiserX** [comment]
I'm routinely hitting into this issue with latest velero version `1.14.1` and restic 0.15.0 (v0.15.0-0-g37d0e1fe5-dirty) compiled with go1.22.6 on linux/amd64

The solution from @optimus-kart is working, but I'm routinely hitting this problem after a week or so (of daily backups). Everything seems to be fine, but then the problem hits again, and I cannot see anything that went bad for the previous backup, but deleting the whole backup or just the podvolumes affected it's the current workaround and it works. 

I would love to see here some mechanism of action to prevent this via software, perhaps avoiding deduplication (so, omitting `--parent` if restic fails to get it, or even better, set `--patent` to a previous earlier backup, as the last one is anyway "corrupted"). At least we wouldn't get these nasty errors.
