### ISSUE TITLE
Pods stuck while waiting for `/restores/data/.velero/<uuid>`

### ISSUE THREAD

**Issue by NaPs** [vmware-tanzu/velero#3867]
**What steps did you take and what happened:**

During restore, pods with attached PVC are stuck while waiting for `/restores/data/.velero/<uuid>` file to be created. Restore process is marked as completed without error but the "done file" is never created.

**What did you expect to happen:**

Pods not stuck indefinitely when restoring a backup.

**The output of the following commands will help us better understand what's going on**:

https://gist.github.com/NaPs/8adb8f715bd2d8939fda0b0b6439a468

(not posting the full velero logs from controller publicly because it will leak some customers informations. I can provide them privately if needed)

**Anything else you would like to add:**

- Command used to start restore: `velero restore create --from-backup daily-20210610020058 --include-namespaces actions`
- If I create the done file manually by entering a shell into the restic-wait container it release the Pod. The restored data looks ok so I conclude that the restoring process is working
- If I delete a stuck pod, it stay stuck in Terminating state and the restic-wait container show this state (I don't know if this is related to my problem):
  ```
    State:          Terminated
      Reason:       ContainerStatusUnknown
      Message:      The container could not be located when the pod was terminated
      Exit Code:    137
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
  ```

**Environment:**

- Velero version (use `velero version`): 1.6.0
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.18.15
- Kubernetes installer & version: OVH
- Cloud provider or hardware configuration: OVH
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS (managed by OVH)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

Thank you!

**Comment by b4tsn** [comment]
I am facing similar issue on velero 1.5.3.

It looks like it is caused by restic pod crash during the restore.

After each restore try, the restarts counter increase:

```
NAME           READY   STATUS    RESTARTS   AGE
restic-gj9hw   1/1     Running   0          10d
restic-khxfr   1/1     Running   0          10d
restic-q72qg   1/1     Running   0          10d
restic-qnqkx   1/1     Running   0          10d
restic-wcc2k   1/1     Running   0          10d
restic-zfzqf   1/1     Running   3          10d 
```

From restic pod logs:

```
E0614 14:55:24.445876       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 357 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1d12940, 0xc00096bc40)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1d12940, 0xc00096bc40)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/vmware-tanzu/velero/pkg/controller.isResticInitContainerRunning(...)
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/pod_volume_restore_controller.go:226
github.com/vmware-tanzu/velero/pkg/controller.(*podVolumeRestoreController).podHandler(0xc0004a0300, 0x1e0e880, 0xc000a82c00)
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/pod_volume_restore_controller.go:178 +0x73d
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /go/pkg/mod/k8s.io/client-go@v0.18.4/tools/cache/controller.go:218
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /go/pkg/mod/k8s.io/client-go@v0.18.4/tools/cache/shared_informer.go:744 +0x129
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000a94760)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000be7f60, 0x2238e60, 0xc000179ec0, 0x1b4b901, 0xc0001608a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a94760, 0x3b9aca00, 0x0, 0xc000711a01, 0xc0001608a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000bc6200)
        /go/pkg/mod/k8s.io/client-go@v0.18.4/tools/cache/shared_informer.go:738 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00073ea00, 0xc00040ef50)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:71 +0x62
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0
```

**Comment by NaPs** [comment]
Hi @b4tsn,

It's maybe not the same issue:

```
$ kubectl -n velero get pod
NAME                      READY   STATUS    RESTARTS   AGE
restic-5hpdp              1/1     Running   0          3d2h
restic-fjlnd              1/1     Running   0          3d2h
restic-rhqc6              1/1     Running   0          3d2h
velero-6c99f8d4c4-jmphq   1/1     Running   0          3d2h
```

**Comment by zubron** [comment]
HI @NaPs - thanks for reporting this, and sorry that you're having problems here. To diagnose this, we would need to see the logs from the restic pods as well as that is where the controller that writes the done file is running. Given that the restic controller runs as a DaemonSet, we will need the logs from the restic pod that is on the same node as the pod that is being deleted. You can find this node, or provide the logs for all of them.

Could you also provide the output of `kubectl get -n velero podvolumerestores.velero.io`? The PodVolumeRestore objects will have some associated status that will help determine if the controller successfully processed the restore. Thanks!

**Comment by zubron** [comment]
@b4tsn This is a separate issue that was fixed in 1.6: #3198. Please upgrade to the latest 1.6 release to make use of this fix: https://velero.io/docs/v1.6/upgrade-to-1.6/

**Comment by NaPs** [comment]
Hi @zubron, sorry for this (too) long silence.

I tried again to do a restore of the same namespace using velero 1.7 this time, but the issue is still occurring.

I updated the gist with the logs of the restic pod running on the same node as the restored workload: https://gist.github.com/NaPs/8adb8f715bd2d8939fda0b0b6439a468#file-restic-logs

Also, here is the output of `kubectl get -n velero podvolumerestores.velero.io`:

```
NAME                    AGE
restore-amillet-q7s8c   8m34s
```

Please note that I did not updated all the other informations in the gist. If it can help, I can redo the whole process with fresh logs. Just let me know :-)

Thank you!
