### ISSUE TITLE
Don't Error with Restic Empty Volumes

### ISSUE THREAD

**Issue by pseymournutanix** [vmware-tanzu/velero#5678]
Please see:- https://github.com/vmware-tanzu/velero/issues/1266

Updated test cluster to 1.10 (restic) and the above issue is now resurfaced.

From old 1.9.x backup:-

```
$ k describe podvolumebackups.velero.io backup-20221212065647-g594v -n velero
...
Spec:
  Backup Storage Location:  default
  Node:                    k8s-worker-3
  Pod:
    Kind:           Pod
    Name:           istio-ingressgateway-6cc9879b9b-gss9d
    Namespace:      istio-system
    UID:            297f7d4d-139e-40c0-9296-ca203481a935
  Repo Identifier:  s3:.../restic/istio-system
  Tags:
    Backup:        backup-20221212065647
    Backup - UID:  b2674ffc-b11e-43c6-8398-a705678fe250
    Ns:            istio-system
    Pod:           istio-ingressgateway-6cc9879b9b-gss9d
    Pod - UID:     297f7d4d-139e-40c0-9296-ca203481a935
    Volume:        workload-socket
  Volume:          workload-socket
Status:
  Completion Timestamp:  2022-12-12T06:59:04Z
  Message:               volume was empty so no snapshot was taken
  Phase:                 Completed
  Progress:
  Start Timestamp:  2022-12-12T06:59:03Z
```

Whereas with 1.10

```
$ k describe podvolumebackups.velero.io test-backup-mkh8l -n velero
...
Spec:
  Backup Storage Location:  default
  Node:                     k8s-worker-5
  Pod:
    Kind:           Pod
    Name:           istio-ingressgateway-6cc9879b9b-fqtdq
    Namespace:      istio-system
    UID:            01ea8189-5f1c-4deb-90d0-72a44409628d
  Repo Identifier:  s3:.../restic/istio-system
  Tags:
    Backup:        test-backup
    Backup - UID:  3321ec28-be9b-485f-9960-055253572621
    Ns:            istio-system
    Pod:           istio-ingressgateway-6cc9879b9b-fqtdq
    Pod - UID:     01ea8189-5f1c-4deb-90d0-72a44409628d
    Volume:        workload-socket
  Uploader Type:   restic
  Volume:          workload-socket
Status:
  Completion Timestamp:  2022-12-12T08:45:12Z
  Message:               running backup, stderr=error running restic backup command restic backup ... stderr: Fatal: unable to save snapshot: snapshot is empty
: error running restic backup command restic backup -... with error: exit status 1 stderr: Fatal: unable to save snapshot: snapshot is empty

  Phase:  Failed
  Progress:
  Start Timestamp:  2022-12-12T08:45:10Z
```

**Comment by reasonerjt** [comment]
@Lyndon-Li @qiuming-best Please clarify if this is a regression if it is, we should fix it in v1.10.1

**Comment by pseymournutanix** [comment]
Hi, I see a fix has been merged any ETA on a release as this makes our monitoring a little off as no backups are successful. Thanks.

**Comment by qiuming-best** [comment]
@pseymournutanix We'll release 1.10.1 around next week, which includes the fix pr. I'll close this issue

**Comment by DysphoricUnicorn** [comment]
Was this actually fixed for you in 1.10.1? @pseymournutanix 

I'm running 1.11.0 and this issue is still appearing.
