### ISSUE TITLE
Retry upload codecov when rate limit is hit.

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#7787]
**What steps did you take and what happened:**

[Following happened.](https://github.com/vmware-tanzu/velero/actions/runs/9007590746/job/24747707600?pr=7762#step:6:54)
```
info - 2024-05-08 19:47:47,812 -- The PR is happening in a forked repo. Using tokenless upload.
info - 2024-05-08 19:47:48,001 -- Process Commit creating complete
debug - 2024-05-08 19:47:48,001 -- Commit creating result --- {"result": "RequestResult(error=RequestError(code='HTTP Error 429', params={}, description='{\"detail\":\"Tokenless has reached GitHub rate limit. Please upload using a token: https://docs.codecov.com/docs/adding-the-codecov-token. Expected available in 197 seconds.\"}'), warnings=[], status_code=429, text='{\"detail\":\"Tokenless has reached GitHub rate limit. Please upload using a token: https://docs.codecov.com/docs/adding-the-codecov-token. Expected available in 197 seconds.\"}')"}
```

**What did you expect to happen:**
This rate limit to not fail Run CI job.

`Expected available in 197 seconds.` from log can be used to wait before retrying again.

**Anything else you would like to add:**

Could potentially be solved via Codecov CLI repo https://github.com/codecov/codecov-cli/issues/441

https://github.com/codecov/feedback/issues/358

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kaovilai** [comment]
https://github.com/codecov/engineering-team/issues/1574

**Comment by kaovilai** [comment]
Should be solved with https://github.com/codecov/codecov-action/commit/7594baaf0c8b9ecdddba6269a6b089f60a3c859a

Already using v4 so should be fine.

**Comment by christianwgd** [comment]
The update doesn't fix anything for me. Does anyone knows an alternative solution for codecov? Doesn't even have to be such a full blown solution.

**Comment by mateusoliveira43** [comment]
we could use Go provided tools

Example command in Makefile 
```make
COVERAGE_THRESHOLD=80

.PHONY: check-coverage
check-coverage: ## Check if test coverage threshold was reached.
	@{ \
	set -e ;\
	current_coverage=$(shell go tool cover -func=cover.out | grep total | grep -Eo "[0-9]+\.[0-9]+") ;\
	if  [ "$$(echo "$$current_coverage < $(COVERAGE_THRESHOLD)" | bc -l)" -eq 1 ];then \
		echo "Current coverage ($$current_coverage%) is below project threshold of $(COVERAGE_THRESHOLD)%" ;\
		exit 1 ;\
	fi ;\
	echo "Coverage threshold of $(COVERAGE_THRESHOLD)% reached: $$current_coverage%" ;\
	}
```
