### ISSUE TITLE
False Errors with 1.16.0 ?

### ISSUE THREAD

**Issue by pseymournutanix** [vmware-tanzu/velero#8873]
Getting lots of spurious errors about backups failing as pods not in a "Running" state when they have been for some time.

```
$ k get pods -A -o wide | grep gh-run-controller-gha-rs-controller-569545fc9d-gn                                                                                                                              
gh-run-controller                 gh-run-controller-gha-rs-controller-569545fc9d-gnwfc              1/1     Running                 1 (148d ago)        399d     172.20.3.233    karbon-canaveral-beta-510acc-k8s-worker-3           <none>           <none>

$  velero backup logs canaveral-services-beta-daily-fs-20250418070044 | grep gh-run-controller-gha-rs-controller-569545fc9d-gnwfc                                                                                                                         ✔
time="2025-04-18T07:00:52Z" level=info msg="Processing item" backup=velero/canaveral-services-beta-daily-fs-20250418070044 logSource="pkg/backup/backup.go:511" name=gh-run-controller-gha-rs-controller-569545fc9d-gnwfc namespace=gh-run-controller progress= resource=pods
time="2025-04-18T07:00:52Z" level=info msg="adding pods gh-run-controller/gh-run-controller-gha-rs-controller-569545fc9d-gnwfc to ItemBlock" backup=velero/canaveral-services-beta-daily-fs-20250418070044 logSource="pkg/backup/itemblock.go:76"
time="2025-04-18T07:00:52Z" level=info msg="Backing Up Item Block including pods gh-run-controller/gh-run-controller-gha-rs-controller-569545fc9d-gnwfc (1 items in block)" backup=velero/canaveral-services-beta-daily-fs-20250418070044 logSource="pkg/backup/backup.go:548"
time="2025-04-18T07:00:52Z" level=info msg="Backing up item" backup=velero/canaveral-services-beta-daily-fs-20250418070044 logSource="pkg/backup/item_backupper.go:187" name=gh-run-controller-gha-rs-controller-569545fc9d-gnwfc namespace=gh-run-controller resource=pods
time="2025-04-18T07:00:52Z" level=info msg="Perform fs-backup action for volume tmp of pod gh-run-controller/gh-run-controller-gha-rs-controller-569545fc9d-gnwfc due to opt-in/out way" backup=velero/canaveral-services-beta-daily-fs-20250418070044 logSource="internal/volumehelper/volume_policy_helper.go:190"
time="2025-04-18T07:00:52Z" level=info msg="Executing custom action" backup=velero/canaveral-services-beta-daily-fs-20250418070044 logSource="pkg/backup/item_backupper.go:360" name=gh-run-controller-gha-rs-controller-569545fc9d-gnwfc namespace=gh-run-controller resource=pods
time="2025-04-18T07:00:52Z" level=info msg="pod gh-run-controller/gh-run-controller-gha-rs-controller-569545fc9d-gnwfc has volumes to backup: [tmp]" backup=velero/canaveral-services-beta-daily-fs-20250418070044 logSource="pkg/podvolume/backupper.go:218" name=gh-run-controller-gha-rs-controller-569545fc9d-gnwfc namespace=gh-run-controller resource=pods
time="2025-04-18T07:00:52Z" level=warning msg="Skip pod volume tmp" backup=velero/canaveral-services-beta-daily-fs-20250418070044 error="daemonset pod not found in running state in node karbon-canaveral-beta-510acc-k8s-worker-3" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/nodeagent/node_agent.go:166" error.function=github.com/vmware-tanzu/velero/pkg/nodeagent.isRunningInNode logSource="pkg/podvolume/backupper.go:455" name=gh-run-controller-gha-rs-controller-569545fc9d-gnwfc namespace=gh-run-controller resource=pods
time="2025-04-18T07:00:52Z" level=info msg="1 errors encountered backup up item" backup=velero/canaveral-services-beta-daily-fs-20250418070044 logSource="pkg/backup/backup.go:859" name=gh-run-controller-gha-rs-controller-569545fc9d-gnwfc
time="2025-04-18T07:00:52Z" level=error msg="Error backing up item" backup=velero/canaveral-services-beta-daily-fs-20250418070044 error="daemonset pod not found in running state in node karbon-canaveral-beta-510acc-k8s-worker-3" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/nodeagent/node_agent.go:166" error.function=github.com/vmware-tanzu/velero/pkg/nodeagent.isRunningInNode logSource="pkg/backup/backup.go:863" name=gh-run-controller-gha-rs-controller-569545fc9d-gnwfc
time="2025-04-18T07:00:52Z" level=info msg="Backed up 119 items out of an estimated total of 4050 (estimate will change throughout the backup)" backup=velero/canaveral-services-beta-daily-fs-20250418070044 kind=Pod logSource="pkg/backup/backup.go:496" name=gh-run-controller-gha-rs-controller-569545fc9d-gnwfc namespace=gh-run-controller progress=
```

Is just one example we are getting over 50 of these in each run when if the pods were not running we would know about it :)

[bundle-2025-04-18-10-18-29.tar.gz](https://github.com/user-attachments/files/19810814/bundle-2025-04-18-10-18-29.tar.gz)

**Comment by Lyndon-Li** [comment]
What is the backup method are you using? e.g., fs-backup or CSI snapshot data movement?

**Comment by pseymournutanix** [comment]
fs-backup this one is. We also run CSI snapshot backups and those are fine. Just since we moved from 1.15.2 to 1.16.0 the FS backups are now producing 49 errors, and 156 warnings on this cluster alone (previously 0)

**Comment by Lyndon-Li** [comment]
> we are getting over 50 of these in each run when if the pods were not running

Do you mean you are backing up pods NOT in running state through fs-backup?

**Comment by pseymournutanix** [comment]
No I mean they are all running it's just the FS backup reports they are not the snapshots are fine. 1.15.2 had no issues with the pods in this way a lot of not restarted for a year.

**Comment by PRBonham** [comment]
This may be caused by the version 9.0.0 helm chart not adding the correct "role" label to the node-agent deamonset pods. See https://github.com/vmware-tanzu/helm-charts/issues/659 for a fix to the helm chart.

I have fixed this on my local setup by adding the below to by Helm values as a temporary workaround:

```yaml
nodeAgent:
  podLabels:
    role: node-agent
```

**Comment by Lyndon-Li** [comment]
@pseymournutanix Please check if you are using Helm to install Velero and the workaround mentioned in https://github.com/vmware-tanzu/velero/issues/8873#issuecomment-2817114016 works for you.

**Comment by pseymournutanix** [comment]
OK this is better the errors have done 

```
$ velero get backups                                                                                                                                                                                                                                                
NAME                                                STATUS            ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
canaveral-services-beta-daily-fs-20250421082410     Completed         0        14         2025-04-21 09:24:11 +0100 BST   2d        default            <none>
canaveral-services-beta-daily-fs-20250421070047     PartiallyFailed   49       156        2025-04-21 08:00:47 +0100 BST   2d        default            <none>
```

We still get warnings for pods not running (and these are not so valid) 
```  Namespaces:
    dolphinscheduler:             resource: /pods name: /dolphinscheduler-postgresql-0 message: /volume data is declared in pod dolphinscheduler/dolphinscheduler-postgresql-0 but not mounted by any container, skipping
    argocd:                       resource: /pods name: /argocd-repo-server-57bdc58494-qhjnv message: /volume var-files is declared in pod argocd/argocd-repo-server-57bdc58494-qhjnv but not mounted by any container, skipping
    canaveral-config-store:       resource: /pods name: /canaveral-config-store-d5f9489b5-lqz67 message: /Skip pod volume workload-socket error: /pod is not in the expected status, name=canaveral-config-store-d5f9489b5-lqz67, namespace=canaveral-config-store, phase=Pending: pod is not running
                                  resource: /pods name: /canaveral-config-store-d5f9489b5-lqz67 message: /Skip pod volume credential-socket error: /pod is not in the expected status, name=canaveral-config-store-d5f9489b5-lqz67, namespace=canaveral-config-store, phase=Pending: pod is not running
                                  resource: /pods name: /canaveral-config-store-d5f9489b5-lqz67 message: /Skip pod volume workload-certs error: /pod is not in the expected status, name=canaveral-config-store-d5f9489b5-lqz67, namespace=canaveral-config-store, phase=Pending: pod is not running
                                  resource: /pods name: /canaveral-config-store-d5f9489b5-lqz67 message: /Skip pod volume istio-envoy error: /pod is not in the expected status, name=canaveral-config-store-d5f9489b5-lqz67, namespace=canaveral-config-store, phase=Pending: pod is not running
                                  resource: /pods name: /canaveral-config-store-d5f9489b5-lqz67 message: /Skip pod volume istio-data error: /pod is not in the expected status, name=canaveral-config-store-d5f9489b5-lqz67, namespace=canaveral-config-store, phase=Pending: pod is not running
                                  resource: /pods name: /canaveral-config-store-d5f9489b5-lqz67 message: /Skip pod volume tls error: /pod is not in the expected status, name=canaveral-config-store-d5f9489b5-lqz67, namespace=canaveral-config-store, phase=Pending: pod is not running
    canaveral-dependency-graph:   resource: /pods name: /canaveral-dependency-graph-5c786f988-8gph9 message: /Skip pod volume workload-socket error: /pod is not scheduled, name=canaveral-dependency-graph-5c786f988-8gph9, namespace=canaveral-dependency-graph, phase=Pending
                                  resource: /pods name: /canaveral-dependency-graph-5c786f988-8gph9 message: /Skip pod volume credential-socket error: /pod is not scheduled, name=canaveral-dependency-graph-5c786f988-8gph9, namespace=canaveral-dependency-graph, phase=Pending
                                  resource: /pods name: /canaveral-dependency-graph-5c786f988-8gph9 message: /Skip pod volume workload-certs error: /pod is not scheduled, name=canaveral-dependency-graph-5c786f988-8gph9, namespace=canaveral-dependency-graph, phase=Pending
                                  resource: /pods name: /canaveral-dependency-graph-5c786f988-8gph9 message: /Skip pod volume istio-envoy error: /pod is not scheduled, name=canaveral-dependency-graph-5c786f988-8gph9, namespace=canaveral-dependency-graph, phase=Pending
                                  resource: /pods name: /canaveral-dependency-graph-5c786f988-8gph9 message: /Skip pod volume istio-data error: /pod is not scheduled, name=canaveral-dependency-graph-5c786f988-8gph9, namespace=canaveral-dependency-graph, phase=Pending
                                  resource: /pods name: /canaveral-dependency-graph-5c786f988-8gph9 message: /Skip pod volume tls error: /pod is not scheduled, name=canaveral-dependency-graph-5c786f988-8gph9, namespace=canaveral-dependency-graph, phase=Pending
```

Pretty sure they never used to surface up but it is fine as the build is marked as "Completed" thanks @Lyndon-Li  and thanks @PRBonham
